version: '3.8'
services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    env_file: .env
    volumes:
      - /data/ra/mongodb:/data/db:rw
  application:
    build:
      context: .
      dockerfile: ci.dockerfile
    restart: always
    ports:
      - "8080:8080"
    env_file: .env
#    environment:
#      GIN_MODE: release
#      MONGO_URI: "mongodb://root:password@mongodb:27017/?authSource=admin"