version: '3.8'
services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    env_file: .env.production
    volumes:
      - /data/:/data/db:rw
  application:
    image: rpolnx/golang-with-ci:${APP_VERSION}
    restart: always
    ports:
      - "8080:8080"
    env_file: .env.production
