version: '3.8'
services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - /data/ra/mongodb:/data/db:rw
  application:
    build:
      context: .
      dockerfile: ci.dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
      GIN_MODE: release
      MONGO_URI: "mongodb://root:password@mongodb:27017/?authSource=admin"