---
- hosts: aws_lightsail
  # connection: local
  gather_facts: false
  become: true
  vars:
    version: "latest"

  tasks:
    - name: Copy docker compose
      copy:
        src: ./infra/docker-compose-prd.yaml
        dest: /data/docker-compose.yaml
        owner: ubuntu
        group: ubuntu
        mode: 0644
    - name: Copy env files
      copy:
        src: ./.env.production
        dest: /data/.env.production
        owner: ubuntu
        group: ubuntu
        mode: 0644
    - name: Deploy Docker Compose stack
      docker_compose:
        project_src: /data
        files:
          - docker-compose.yaml
      environment:
        APP_VERSION: "{{ version }}"
