---
- hosts: aws_lightsail
  # connection: local
  gather_facts: false
  become: true
  vars:
    version: "latest"
    user: "ubuntu"

  tasks:
    - name: Creates mongo data
      file:
        path: /data
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: 0775
    - name: Creates application folder
      file:
        path: /usr/app
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: 0775
    - name: Copy docker compose
      copy:
        src: ../docker-compose-prd.yaml
        dest: /usr/app/docker-compose.yaml
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: 0644
    - name: Deploy Docker Compose stack
      docker_compose:
        project_src: /usr/app
        files:
          - docker-compose.yaml
      environment:
        APP_VERSION: "{{ version }}"
