---
- hosts: aws_lightsail
  # connection: local
  gather_facts: false
  become: true
  vars:
    version: "latest"

  tasks:
    # In case of error, install docker from py3
    # https://stackoverflow.com/questions/59384708/ansible-returns-with-failed-to-import-the-required-python-library-docker-sdk-f
    - name: Copy docker compose
      copy:
        src: ./infra/docker-compose-prd.yaml
        dest: /data/docker-compose.yaml
        owner: ubuntu
        group: ubuntu
        mode: 0644
    - name: Copy env files
      copy:
        src: ./.env.production
        dest: /data/.env.production
        owner: ubuntu
        group: ubuntu
        mode: 0644
    - name: Deploy Docker Compose stack
      docker_compose:
        project_src: ../../
        files:
          - docker-compose.yaml
      environment:
        APP_VERSION: "{{ version }}"
