name: "Golang CI"

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set GO
        uses: actions/setup-go@v2
        with:
          go-version: "^1.17.6"

      - name: Install dependencies
        run: go mod download -x

      - name: Install swag cli
        run: go install github.com/swaggo/swag/cmd/swag@latest

      - name: Run tests
        run: go test -v ./test/...

      - name: Generate docs
        run: $(go env GOPATH)/bin/swag init -g main.go

      - name: Build
        run: go build main.go

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ github.run_number }}

      - name: Image digest
        run: echo "Finalized with image ID ${{ steps.docker_build.outputs.digest }} - Build Number \#${{ github.run_number }}"

      - name: Invoke workflow with inputs
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Golang CD
          token: ${{ secrets.PERSONAL_TOKEN }}
          inputs: '{ "image-version": "${{ github.run_number }}" }'
